package com.ariai.app.util

// Persian UI strings keyed by the English text used in the code.
internal val faStrings: Map<String, String> = mapOf(
        "Rename chat" to "تغییر نام گفتگو",
        "Chat title" to "عنوان گفتگو",
        "A more personal AI." to "یک هوش مصنوعی شخصی‌تر.",
        "AI Providers" to "ارائه‌دهنده‌های هوش مصنوعی",
        "AI news today" to "خبرهای امروز هوش مصنوعی",
        "AI" to "هوش مصنوعی",
        "API key" to "کلید API",
        "About AriAI" to "درباره AriAI",
        "About" to "درباره",
        "Accent Color" to "رنگ تأکیدی",
        "Accepts images" to "پذیرش تصویر",
        "Active" to "فعال",
        "Add Custom Provider" to "افزودن ارائه‌دهنده‌ی سفارشی",
        "Add MCP server" to "افزودن سرور MCP",
        "Add Provider" to "افزودن ارائه‌دهنده",
        "Add a provider first" to "ابتدا یک ارائه‌دهنده اضافه کنید",
        "Add a provider with at least one model." to "یک ارائه‌دهنده با حداقل یک مدل اضافه کنید.",
        "Add header" to "افزودن هدر",
        "Add model" to "افزودن مدل",
        "Add provider" to "افزودن ارائه‌دهنده",
        "Add server" to "افزودن سرور",
        "Add to favorites" to "افزودن به علاقه‌مندی‌ها",
        "Add to message" to "افزودن به پیام",
        "Add your first AI provider to start chatting" to "اولین ارائه‌دهنده‌ی هوش مصنوعی را اضافه کنید تا گفتگو شروع شود",
        "Add" to "افزودن",
        "Advanced" to "پیشرفته",
        "All chats deleted" to "همه‌ی گفتگوها حذف شد",
        "All" to "همه",
        "Any OpenAI-compatible API" to "هر API سازگار با OpenAI",
        "Appearance" to "ظاهر",
        "AriAI chat list" to "فهرست گفتگوهای AriAI",
        "AriAI currently ships in English only." to "AriAI فعلاً فقط انگلیسی است.",
        "AriAI v1.0 - Personal AI" to "AriAI نسخه‌ی ۱.۰ - هوش مصنوعی شخصی",
        "Attachments" to "پیوست‌ها",
        "Back" to "بازگشت",
        "Base URL" to "آدرس پایه",
        "Basic" to "ساده",
        "Branch" to "شاخه",
        "Built into the provider (Gemini)" to "داخل خود ارائه‌دهنده (Gemini)",
        "Built-in Tools" to "ابزارهای داخلی",
        "Camera" to "دوربین",
        "Cancel" to "انصراف",
        "Chat options" to "تنظیمات گفتگو",
        "Chat options, text size, theme" to "تنظیمات گفتگو، اندازه‌ی متن، تم",
        "Chat" to "گفتگو",
        "Chats" to "گفتگوها",
        "Choose model" to "انتخاب مدل",
        "Claude models" to "مدل‌های Claude",
        "Close" to "بستن",
        "Cloud" to "ابری",
        "Collapse" to "بستن فهرست",
        "Compress History" to "فشرده‌سازی تاریخچه",
        "Compress history" to "فشرده‌سازی تاریخچه",
        "Connect local tools" to "اتصال ابزارهای محلی",
        "Connect. Mix. Create." to "متصل شو. ترکیب کن. بساز.",
        "Connected" to "متصل",
        "Connection" to "اتصال",
        "Conversation" to "گفتگو",
        "Copied" to "کپی شد",
        "Copy conversation" to "کپی گفتگو",
        "Copy" to "کپی",
        "Custom body (JSON)" to "بدنه‌ی سفارشی (JSON)",
        "Custom headers" to "هدرهای سفارشی",
        "Custom" to "سفارشی",
        "Dark" to "تیره",
        "Data & Sync" to "داده و همگام‌سازی",
        "Data & storage" to "داده و فضای ذخیره",
        "Data" to "داده",
        "Default model" to "مدل پیش‌فرض",
        "Default thinking depth" to "عمق تفکر پیش‌فرض",
        "Delete all chats?" to "همه‌ی گفتگوها حذف شود؟",
        "Delete all chats" to "حذف همه‌ی گفتگوها",
        "Delete all" to "حذف همه",
        "Delete provider?" to "ارائه‌دهنده حذف شود؟",
        "Delete provider" to "حذف ارائه‌دهنده",
        "Delete" to "حذف",
        "Disabled" to "غیرفعال",
        "Display name (optional)" to "نام نمایشی (اختیاری)",
        "Docs" to "مستندات",
        "Earlier messages compressed" to "پیام‌های قبلی فشرده شد",
        "Earlier" to "قبلی",
        "Edit image" to "ویرایش تصویر",
        "Edit provider" to "ویرایش ارائه‌دهنده",
        "Edit" to "ویرایش",
        "Empty response from API" to "پاسخ خالی از API",
        "Enable" to "فعال‌سازی",
        "English" to "انگلیسی",
        "Expand message" to "باز کردن پیام",
        "Expand" to "باز کردن",
        "Explain quantum computing simply" to "محاسبات کوانتومی را ساده توضیح بده",
        "Export chat list" to "خروجی فهرست گفتگوها",
        "Export list, storage overview" to "خروجی فهرست، مرور فضای ذخیره",
        "Extensions" to "افزونه‌ها",
        "Extra headers for this model only." to "هدرهای اضافی فقط برای این مدل.",
        "Favorites" to "علاقه‌مندی‌ها",
        "Fetch" to "دریافت مدل‌ها",
        "Filter models" to "فیلتر مدل‌ها",
        "Function calling" to "فراخوانی تابع",
        "Gemini models, with Search and URL tools" to "مدل‌های Gemini، همراه با ابزارهای جستجو و URL",
        "General" to "عمومی",
        "Generate" to "ساختن",
        "Generated image" to "تصویر ساخته‌شده",
        "Generated video" to "ویدیوی ساخته‌شده",
        "Generating video…" to "در حال ساخت ویدیو…",
        "Glass Design" to "طراحی شیشه‌ای",
        "Google Search grounding" to "جستجوی گوگل",
        "Google results via API" to "نتایج گوگل از طریق API",
        "Header" to "هدر",
        "Hide key" to "پنهان کردن کلید",
        "How can I help you?" to "چطور می‌توانم کمک کنم؟",
        "Image chat" to "گفتگوی تصویری",
        "Image mode" to "حالت تصویر",
        "Image" to "تصویر",
        "Import provider" to "وارد کردن ارائه‌دهنده",
        "Import" to "وارد کردن",
        "Independent web index" to "ایندکس مستقل وب",
        "Language" to "زبان",
        "Large" to "بزرگ",
        "Light" to "روشن",
        "Loaded from the API on save" to "هنگام ذخیره از API خوانده می‌شود",
        "Loading image…" to "در حال بارگذاری تصویر…",
        "Loading models…" to "در حال دریافت مدل‌ها…",
        "Loading…" to "در حال بارگذاری…",
        "Local search" to "جستجوی محلی",
        "Local" to "محلی",
        "MCP servers" to "سرورهای MCP",
        "Manage MCP tool servers" to "مدیریت سرورهای ابزار MCP",
        "Medium" to "متوسط",
        "Message AriAI" to "پیام به AriAI",
        "Message text size" to "اندازه‌ی متن پیام",
        "Message" to "پیام",
        "Model Context Protocol" to "پروتکل Model Context",
        "Model ID" to "شناسه‌ی مدل",
        "Model search" to "جستجوی مدل",
        "Models & services" to "مدل‌ها و سرویس‌ها",
        "Models that run on your own computer" to "مدل‌هایی که روی کامپیوتر خودتان اجرا می‌شوند",
        "Models" to "مدل‌ها",
        "More" to "بیشتر",
        "Must be a JSON object" to "باید یک شیء JSON باشد",
        "Name" to "نام",
        "New Chat" to "گفتگوی جدید",
        "New chat" to "گفتگوی جدید",
        "New chats start with this model." to "گفتگوهای جدید با این مدل شروع می‌شوند.",
        "Next message makes a video" to "پیام بعدی ویدیو می‌سازد",
        "Next message makes an image" to "پیام بعدی تصویر می‌سازد",
        "No MCP servers yet" to "هنوز سرور MCP ندارید",
        "No conversations yet" to "هنوز گفتگویی نیست",
        "No image returned" to "تصویری برگردانده نشد",
        "No key yet. Tap to set up" to "کلید ندارید. برای تنظیم بزنید",
        "No key" to "بدون کلید",
        "No match" to "موردی پیدا نشد",
        "No matches" to "موردی پیدا نشد",
        "No models available" to "مدلی در دسترس نیست",
        "No models yet" to "هنوز مدلی نیست",
        "No models" to "مدلی نیست",
        "No providers yet" to "هنوز ارائه‌دهنده‌ای نیست",
        "No video model. Fetch models in provider settings." to "مدل ویدیویی نیست. در تنظیمات ارائه‌دهنده مدل‌ها را دریافت کنید.",
        "Not a valid provider JSON" to "JSON ارائه‌دهنده معتبر نیست",
        "Not chosen" to "انتخاب نشده",
        "Not enough messages to compress yet" to "هنوز پیام کافی برای فشرده‌سازی نیست",
        "Older messages compressed" to "پیام‌های قدیمی‌تر فشرده شد",
        "Ollama (local)" to "Ollama (محلی)",
        "Only for Gemini providers" to "فقط برای ارائه‌دهنده‌های Gemini",
        "Open menu" to "باز کردن منو",
        "Open models" to "باز کردن مدل‌ها",
        "Open" to "باز کردن",
        "OpenAI compatible" to "سازگار با OpenAI",
        "OpenAI, Gemini, Claude and more" to "OpenAI، Gemini، Claude و بیشتر",
        "Paste a provider as JSON with name, type, baseUrl and apiKey." to "ارائه‌دهنده را با نام، نوع، baseUrl و apiKey به صورت JSON بچسبانید.",
        "Personal Workspace" to "فضای کاری شخصی",
        "Photo" to "عکس",
        "Pin" to "سنجاق کردن",
        "Pinned" to "سنجاق‌شده",
        "Popular Providers" to "ارائه‌دهنده‌های محبوب",
        "Preferences" to "تنظیمات",
        "Premium" to "پریمیوم",
        "Press to search with AI" to "برای جستجو با هوش مصنوعی فشار دهید",
        "Preview: the quick brown fox jumps over the lazy dog." to "پیش‌نمایش: متن نمونه برای تنظیم اندازه‌ی خط.",
        "Privacy" to "حریم خصوصی",
        "Provider" to "ارائه‌دهنده",
        "Providers" to "ارائه‌دهنده‌ها",
        "Providers:" to "ارائه‌دهنده‌ها:",
        "Python best practices" to "بهترین روش‌های پایتون",
        "Quantum computing" to "محاسبات کوانتومی",
        "Read the links in the message" to "خواندن لینک‌های داخل پیام",
        "Recent searches" to "جستجوهای اخیر",
        "Recommended providers" to "ارائه‌دهنده‌های پیشنهادی",
        "Remove attachment" to "حذف پیوست",
        "Remove every conversation" to "حذف همه‌ی گفتگوها",
        "Remove from favorites" to "حذف از علاقه‌مندی‌ها",
        "Remove header" to "حذف هدر",
        "Remove model" to "حذف مدل",
        "Remove server" to "حذف سرور",
        "Remove" to "حذف",
        "Removes every conversation on this device" to "همه‌ی گفتگوها را از این دستگاه حذف می‌کند",
        "Research-focused search API" to "API جستجوی تحقیقاتی",
        "Retry" to "تلاش دوباره",
        "Save failed" to "ذخیره نشد",
        "Save" to "ذخیره",
        "Saved to Pictures/AriAI" to "در Pictures/AriAI ذخیره شد",
        "Saved" to "ذخیره شد",
        "Saving needs Android 10 or newer" to "ذخیره به اندروید ۱۰ یا جدیدتر نیاز دارد",
        "Search chats" to "جستجوی گفتگوها",
        "Search conversations" to "جستجوی گفتگوها",
        "Search models" to "جستجوی مدل‌ها",
        "Search providers" to "جستجوی ارائه‌دهنده‌ها",
        "Search service" to "سرویس جستجو",
        "Search web or chat history" to "جستجوی وب یا تاریخچه‌ی گفتگو",
        "Search" to "جستجو",
        "Selected" to "انتخاب‌شده",
        "Semantic neural search" to "جستجوی معنایی عصبی",
        "Send" to "ارسال",
        "Server URL" to "آدرس سرور",
        "Settings" to "تنظیمات",
        "Share a text list of your conversations" to "فهرست متنی گفتگوهایتان را به اشتراک بگذارید",
        "Share" to "اشتراک‌گذاری",
        "Show key" to "نمایش کلید",
        "Show less" to "نمایش کمتر",
        "Small settings." to "تنظیمات کوچک.",
        "Small" to "کوچک",
        "Start a new chat to begin" to "برای شروع یک گفتگوی جدید بسازید",
        "Stored locally on this device" to "فقط روی همین دستگاه ذخیره می‌شود",
        "Stored only on this device." to "فقط روی همین دستگاه ذخیره می‌شود.",
        "Summarize older messages to save context" to "خلاصه‌سازی پیام‌های قدیمی برای صرفه‌جویی در متن",
        "System" to "سیستم",
        "Take Picture" to "گرفتن عکس",
        "Tap the star icon for recommended providers, or + to add one." to "برای ارائه‌دهنده‌های پیشنهادی روی ستاره، یا برای افزودن یکی روی + بزنید.",
        "Tap to choose a model" to "برای انتخاب مدل بزنید",
        "Test" to "آزمایش",
        "Text file" to "فایل متنی",
        "Theme" to "تم",
        "Thinking depth" to "عمق تفکر",
        "This removes every conversation on this device. It cannot be undone." to "همه‌ی گفتگوها از این دستگاه حذف می‌شود. این کار برگشت ندارد.",
        "Today" to "امروز",
        "Tool calling" to "فراخوانی ابزار",
        "Tools the API runs for this model." to "ابزارهایی که API برای این مدل اجرا می‌کند.",
        "Tools" to "ابزارها",
        "Transport" to "نوع انتقال",
        "Try another name." to "نام دیگری امتحان کنید.",
        "Turn off search" to "خاموش کردن جستجو",
        "Type a message below to start." to "برای شروع، پیامی پایین بنویسید.",
        "Type" to "نوع",
        "URL context" to "زمینه‌ی URL",
        "Unpin" to "برداشتن سنجاق",
        "Upload File" to "بارگذاری فایل",
        "Use this server in chats" to "استفاده از این سرور در گفتگوها",
        "Used for new messages. You can change it per message in the chat." to "برای پیام‌های جدید استفاده می‌شود. می‌توانید برای هر پیام در گفتگو تغییرش دهید.",
        "Uses your search service" to "از سرویس جستجوی شما استفاده می‌کند",
        "Value" to "مقدار",
        "Version 1.0" to "نسخه‌ی ۱.۰",
        "Video" to "ویدیو",
        "Vision input" to "ورودی تصویر",
        "Vision" to "بینایی تصویری",
        "Voice" to "صدا",
        "Wait for the reply to finish first" to "اول صبر کنید تا پاسخ تمام شود",
        "Web Search" to "جستجوی وب",
        "Web search for answers" to "جستجوی وب برای پاسخ",
        "Web search" to "جستجوی وب",
        "Web" to "وب",
        "What should change?" to "چه چیزی باید تغییر کند؟",
        "Write a Python function" to "یک تابع پایتون بنویس",
        "Yesterday" to "دیروز",
        "Connect MCP servers so the model can call external tools. Only enabled servers are used." to "سرورهای MCP را وصل کنید تا مدل بتواند ابزارهای بیرونی را صدا بزند. فقط سرورهای فعال استفاده می‌شوند.",
        "Web search:" to "جستجوی وب:",
        "Search for" to "جستجو برای",
        "Large, Medium, Small" to "بزرگ، متوسط، کوچک",
        "🔑 Invalid API key. Please check your provider settings in AI Providers." to "🔑 کلید API نامعتبر است. تنظیمات ارائه‌دهنده را بررسی کنید.",
        "⏳ Rate limit exceeded. Please wait a moment or try another provider." to "⏳ محدودیت تعداد درخواست. کمی صبر کنید یا ارائه‌دهنده‌ی دیگری را امتحان کنید.",
        "🌐 No internet connection. Please check your network." to "🌐 اتصال اینترنت برقرار نیست. شبکه را بررسی کنید.",
    )
