package com.ariai.app.util

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    val appName: String,
    val chats: String,
    val agents: String,
    val settings: String,
    val providers: String,
    val newChat: String,
    val noChats: String,
    val typeMessage: String,
    val send: String,
    val addProvider: String,
    val providerName: String,
    val baseUrl: String,
    val apiKey: String,
    val providerType: String,
    val save: String,
    val cancel: String,
    val delete: String,
    val edit: String,
    val search: String,
    val imageGen: String,
    val webSearch: String,
    val settingsLanguage: String,
    val settingsTheme: String,
    val settingsSearchKeys: String,
    val light: String,
    val dark: String,
    val system: String,
    val english: String,
    val persian: String,
    val arabic: String,
    val turkish: String,
    val german: String,
    val french: String,
    val chatSettings: String,
    val memory: String,
    val model: String,
    val agent: String,
    val general: String,
    val code: String,
    val writer: String,
    val translator: String,
    val researcher: String,
    val artist: String,
    val branch: String,
    val regenerate: String,
    val copy: String,
    val share: String,
    val searchPlaceholder: String,
    val imagePromptPlaceholder: String,
    val generate: String,
    val noProviders: String,
    val addFirstProvider: String,
    val welcomeTitle: String,
    val welcomeDesc: String,
    val continueStr: String,
    val temperature: String,
    val topP: String,
    val systemPrompt: String,
    val about: String,
    val version: String,
    val rikkaHubInspired: String
)

val LocalStrings = compositionLocalOf { englishStrings }

val englishStrings = AppStrings(
    appName = "AriAi",
    chats = "Chats",
    agents = "Agents",
    settings = "Settings",
    providers = "Providers",
    newChat = "New Chat",
    noChats = "No chats yet",
    typeMessage = "Type a message...",
    send = "Send",
    addProvider = "Add Provider",
    providerName = "Provider Name",
    baseUrl = "Base URL",
    apiKey = "API Key",
    providerType = "Provider Type",
    save = "Save",
    cancel = "Cancel",
    delete = "Delete",
    edit = "Edit",
    search = "Search",
    imageGen = "Image Generation",
    webSearch = "Web Search",
    settingsLanguage = "Language",
    settingsTheme = "Theme",
    settingsSearchKeys = "Search API Keys",
    light = "Light",
    dark = "Dark",
    system = "System",
    english = "English",
    persian = "Persian",
    arabic = "Arabic",
    turkish = "Turkish",
    german = "German",
    french = "French",
    chatSettings = "Chat Settings",
    memory = "Memory",
    model = "Model",
    agent = "Agent",
    general = "General",
    code = "Code",
    writer = "Writer",
    translator = "Translator",
    researcher = "Researcher",
    artist = "Artist",
    branch = "Branch",
    regenerate = "Regenerate",
    copy = "Copy",
    share = "Share",
    searchPlaceholder = "Search the web...",
    imagePromptPlaceholder = "Describe the image you want...",
    generate = "Generate",
    noProviders = "No providers configured",
    addFirstProvider = "Add your first AI provider to start chatting",
    welcomeTitle = "Welcome to AriAi",
    welcomeDesc = "Powerful AI client like RikkaHub - Connect your own API keys and chat with any model",
    continueStr = "Continue",
    temperature = "Temperature",
    topP = "Top P",
    systemPrompt = "System Prompt",
    about = "About",
    version = "Version",
    rikkaHubInspired = "Inspired by RikkaHub - The ultimate AI client"
)

val persianStrings = AppStrings(
    appName = "آریاای",
    chats = "گفتگوها",
    agents = "دستیارها",
    settings = "تنظیمات",
    providers = "ارائه‌دهندگان",
    newChat = "چت جدید",
    noChats = "هنوز چتی وجود ندارد",
    typeMessage = "پیام خود را بنویسید...",
    send = "ارسال",
    addProvider = "افزودن ارائه‌دهنده",
    providerName = "نام ارائه‌دهنده",
    baseUrl = "آدرس پایه",
    apiKey = "کلید API",
    providerType = "نوع ارائه‌دهنده",
    save = "ذخیره",
    cancel = "لغو",
    delete = "حذف",
    edit = "ویرایش",
    search = "جستجو",
    imageGen = "ساخت تصویر",
    webSearch = "جستجوی وب",
    settingsLanguage = "زبان",
    settingsTheme = "تم",
    settingsSearchKeys = "کلیدهای جستجو",
    light = "روشن",
    dark = "تاریک",
    system = "سیستم",
    english = "انگلیسی",
    persian = "فارسی",
    arabic = "عربی",
    turkish = "ترکی",
    german = "آلمانی",
    french = "فرانسوی",
    chatSettings = "تنظیمات چت",
    memory = "حافظه",
    model = "مدل",
    agent = "دستیار",
    general = "عمومی",
    code = "کدنویسی",
    writer = "نویسندگی",
    translator = "مترجم",
    researcher = "پژوهشگر",
    artist = "هنرمند",
    branch = "شاخه‌سازی",
    regenerate = "بازتولید",
    copy = "کپی",
    share = "اشتراک‌گذاری",
    searchPlaceholder = "در وب جستجو کنید...",
    imagePromptPlaceholder = "تصویری که می‌خواهید را توصیف کنید...",
    generate = "تولید",
    noProviders = "ارائه‌دهنده‌ای تنظیم نشده",
    addFirstProvider = "اولین ارائه‌دهنده هوش مصنوعی خود را اضافه کنید",
    welcomeTitle = "به آریاای خوش آمدید",
    welcomeDesc = "کلاینت قدرتمند هوش مصنوعی مثل RikkaHub - با API خودتان به هر مدلی متصل شوید",
    continueStr = "ادامه",
    temperature = "خلاقیت",
    topP = "تنوع",
    systemPrompt = "دستورالعمل سیستم",
    about = "درباره",
    version = "نسخه",
    rikkaHubInspired = "الهام گرفته از RikkaHub - بهترین کلاینت هوش مصنوعی"
)

val arabicStrings = AppStrings(
    appName = "آريا آي",
    chats = "المحادثات",
    agents = "المساعدون",
    settings = "الإعدادات",
    providers = "المزودون",
    newChat = "محادثة جديدة",
    noChats = "لا توجد محادثات بعد",
    typeMessage = "اكتب رسالة...",
    send = "إرسال",
    addProvider = "إضافة مزود",
    providerName = "اسم المزود",
    baseUrl = "الرابط الأساسي",
    apiKey = "مفتاح API",
    providerType = "نوع المزود",
    save = "حفظ",
    cancel = "إلغاء",
    delete = "حذف",
    edit = "تعديل",
    search = "بحث",
    imageGen = "توليد الصور",
    webSearch = "البحث في الويب",
    settingsLanguage = "اللغة",
    settingsTheme = "المظهر",
    settingsSearchKeys = "مفاتيح البحث",
    light = "فاتح",
    dark = "داكن",
    system = "النظام",
    english = "الإنجليزية",
    persian = "الفارسية",
    arabic = "العربية",
    turkish = "التركية",
    german = "الألمانية",
    french = "الفرنسية",
    chatSettings = "إعدادات المحادثة",
    memory = "الذاكرة",
    model = "النموذج",
    agent = "المساعد",
    general = "عام",
    code = "البرمجة",
    writer = "الكتابة",
    translator = "المترجم",
    researcher = "الباحث",
    artist = "الفنان",
    branch = "التفرع",
    regenerate = "إعادة توليد",
    copy = "نسخ",
    share = "مشاركة",
    searchPlaceholder = "ابحث في الويب...",
    imagePromptPlaceholder = "صف الصورة التي تريدها...",
    generate = "توليد",
    noProviders = "لم يتم تكوين أي مزود",
    addFirstProvider = "أضف أول مزود ذكاء اصطناعي لبدء الدردشة",
    welcomeTitle = "مرحبا بكم في آريا آي",
    welcomeDesc = "عميل ذكاء اصطناعي قوي مثل RikkaHub",
    continueStr = "متابعة",
    temperature = "الإبداع",
    topP = "التنوع",
    systemPrompt = "موجه النظام",
    about = "حول",
    version = "الإصدار",
    rikkaHubInspired = "مستوحى من RikkaHub"
)

val turkishStrings = AppStrings(
    appName = "AriAi",
    chats = "Sohbetler",
    agents = "Asistanlar",
    settings = "Ayarlar",
    providers = "Sağlayıcılar",
    newChat = "Yeni Sohbet",
    noChats = "Henüz sohbet yok",
    typeMessage = "Bir mesaj yaz...",
    send = "Gönder",
    addProvider = "Sağlayıcı Ekle",
    providerName = "Sağlayıcı Adı",
    baseUrl = "Temel URL",
    apiKey = "API Anahtarı",
    providerType = "Sağlayıcı Türü",
    save = "Kaydet",
    cancel = "İptal",
    delete = "Sil",
    edit = "Düzenle",
    search = "Ara",
    imageGen = "Görsel Oluşturma",
    webSearch = "Web Arama",
    settingsLanguage = "Dil",
    settingsTheme = "Tema",
    settingsSearchKeys = "Arama API Anahtarları",
    light = "Açık",
    dark = "Koyu",
    system = "Sistem",
    english = "İngilizce",
    persian = "Farsça",
    arabic = "Arapça",
    turkish = "Türkçe",
    german = "Almanca",
    french = "Fransızca",
    chatSettings = "Sohbet Ayarları",
    memory = "Hafıza",
    model = "Model",
    agent = "Asistan",
    general = "Genel",
    code = "Kod",
    writer = "Yazar",
    translator = "Çevirmen",
    researcher = "Araştırmacı",
    artist = "Sanatçı",
    branch = "Dallandır",
    regenerate = "Yeniden Oluştur",
    copy = "Kopyala",
    share = "Paylaş",
    searchPlaceholder = "Web'de ara...",
    imagePromptPlaceholder = "İstediğiniz görseli tarif edin...",
    generate = "Oluştur",
    noProviders = "Yapılandırılmış sağlayıcı yok",
    addFirstProvider = "Sohbete başlamak için ilk AI sağlayıcınızı ekleyin",
    welcomeTitle = "AriAi'ye Hoş Geldiniz",
    welcomeDesc = "RikkaHub gibi güçlü AI istemcisi",
    continueStr = "Devam",
    temperature = "Yaratıcılık",
    topP = "Çeşitlilik",
    systemPrompt = "Sistem İstemİ",
    about = "Hakkında",
    version = "Versiyon",
    rikkaHubInspired = "RikkaHub'dan ilham alındı"
)

val germanStrings = AppStrings(
    appName = "AriAi",
    chats = "Chats",
    agents = "Agenten",
    settings = "Einstellungen",
    providers = "Anbieter",
    newChat = "Neuer Chat",
    noChats = "Noch keine Chats",
    typeMessage = "Nachricht eingeben...",
    send = "Senden",
    addProvider = "Anbieter hinzufügen",
    providerName = "Anbietername",
    baseUrl = "Basis-URL",
    apiKey = "API-Schlüssel",
    providerType = "Anbietertyp",
    save = "Speichern",
    cancel = "Abbrechen",
    delete = "Löschen",
    edit = "Bearbeiten",
    search = "Suche",
    imageGen = "Bildgenerierung",
    webSearch = "Websuche",
    settingsLanguage = "Sprache",
    settingsTheme = "Thema",
    settingsSearchKeys = "Such-API-Schlüssel",
    light = "Hell",
    dark = "Dunkel",
    system = "System",
    english = "Englisch",
    persian = "Persisch",
    arabic = "Arabisch",
    turkish = "Türkisch",
    german = "Deutsch",
    french = "Französisch",
    chatSettings = "Chat-Einstellungen",
    memory = "Gedächtnis",
    model = "Modell",
    agent = "Agent",
    general = "Allgemein",
    code = "Code",
    writer = "Autor",
    translator = "Übersetzer",
    researcher = "Forscher",
    artist = "Künstler",
    branch = "Verzweigen",
    regenerate = "Neu generieren",
    copy = "Kopieren",
    share = "Teilen",
    searchPlaceholder = "Im Web suchen...",
    imagePromptPlaceholder = "Beschreiben Sie das gewünschte Bild...",
    generate = "Generieren",
    noProviders = "Keine Anbieter konfiguriert",
    addFirstProvider = "Fügen Sie Ihren ersten KI-Anbieter hinzu",
    welcomeTitle = "Willkommen bei AriAi",
    welcomeDesc = "Leistungsstarker KI-Client wie RikkaHub",
    continueStr = "Weiter",
    temperature = "Kreativität",
    topP = "Vielfalt",
    systemPrompt = "System-Prompt",
    about = "Über",
    version = "Version",
    rikkaHubInspired = "Inspiriert von RikkaHub"
)

val frenchStrings = AppStrings(
    appName = "AriAi",
    chats = "Discussions",
    agents = "Agents",
    settings = "Paramètres",
    providers = "Fournisseurs",
    newChat = "Nouveau Chat",
    noChats = "Pas encore de discussions",
    typeMessage = "Tapez un message...",
    send = "Envoyer",
    addProvider = "Ajouter un fournisseur",
    providerName = "Nom du fournisseur",
    baseUrl = "URL de base",
    apiKey = "Clé API",
    providerType = "Type de fournisseur",
    save = "Enregistrer",
    cancel = "Annuler",
    delete = "Supprimer",
    edit = "Modifier",
    search = "Rechercher",
    imageGen = "Génération d'images",
    webSearch = "Recherche Web",
    settingsLanguage = "Langue",
    settingsTheme = "Thème",
    settingsSearchKeys = "Clés API de recherche",
    light = "Clair",
    dark = "Sombre",
    system = "Système",
    english = "Anglais",
    persian = "Persan",
    arabic = "Arabe",
    turkish = "Turc",
    german = "Allemand",
    french = "Français",
    chatSettings = "Paramètres de chat",
    memory = "Mémoire",
    model = "Modèle",
    agent = "Agent",
    general = "Général",
    code = "Code",
    writer = "Écrivain",
    translator = "Traducteur",
    researcher = "Chercheur",
    artist = "Artiste",
    branch = "Brancher",
    regenerate = "Régénérer",
    copy = "Copier",
    share = "Partager",
    searchPlaceholder = "Rechercher sur le web...",
    imagePromptPlaceholder = "Décrivez l'image que vous voulez...",
    generate = "Générer",
    noProviders = "Aucun fournisseur configuré",
    addFirstProvider = "Ajoutez votre premier fournisseur IA",
    welcomeTitle = "Bienvenue sur AriAi",
    welcomeDesc = "Client IA puissant comme RikkaHub",
    continueStr = "Continuer",
    temperature = "Créativité",
    topP = "Diversité",
    systemPrompt = "Prompt système",
    about = "À propos",
    version = "Version",
    rikkaHubInspired = "Inspiré par RikkaHub"
)

fun getStringsForLanguage(lang: String): AppStrings {
    return when (lang) {
        "fa" -> persianStrings
        "ar" -> arabicStrings
        "tr" -> turkishStrings
        "de" -> germanStrings
        "fr" -> frenchStrings
        else -> englishStrings
    }
}
